services:
  users-db:
    image: postgres:16
    networks:
      - internal
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - users-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      # test: ["CMD", "echo", "3"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  users-service:
    build: ./users_service
    networks:
      - internal
    environment:
      POSTGRES_HOST: users-db
    depends_on:
      users-db:
        condition: service_healthy

  backend-db:
    image: postgres:16
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    networks:
      - internal
    environment:
      POSTGRES_HOST: backend-db
    depends_on:
      backend-db:
        condition: service_healthy

  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - users-service
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal


volumes:
  users-db-data:
  backend-db-data:

networks:
  internal:
    driver: bridge
