services:
  worker:
    build: ./worker
    environment:
      ARTICLE_DB_HOST: backend-db
      USER_DB_HOST: users-db
      PUSH_URL: "http://push-notificator:8000/api/v1/notify"
      ARTICLE_SERVICE_URL: "http://backend:8000"
      REDIS_URL: "redis://redis:6379/0"
    networks:
      - internal
    depends_on:
      redis:
        condition: service_healthy

  push-notificator:
    image: ghcr.io/ayusavin/push-notification-playground:1.0.0
    networks:
      - internal
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  users-db:
    image: postgres:16
    networks:
      - internal
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - users-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  users-service:
    build: ./users_service
    networks:
      - internal
    environment:
      POSTGRES_HOST: users-db
    depends_on:
      users-db:
        condition: service_healthy

  backend-db:
    image: postgres:16
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    networks:
      - internal
    environment:
      POSTGRES_HOST: backend-db
    depends_on:
      backend-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      users-service:
        condition: service_started
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal


volumes:
  users-db-data:
  backend-db-data:

networks:
  internal:
    driver: bridge
